# Generated by Django 6.0.1 on 2026-01-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_app_collection (title)
            VALUES ('collection1')
        """, """
            DELETE FROM store_app_collection
            WHERE title='collection1'
        """)
    ]
